# Generated by Django 5.1 on 2024-11-10 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lapp', '0002_rename_usuario_user_locker_delete_casillero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Usuario',
        ),
        migrations.CreateModel(
            name='Casillero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lapp.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Locker',
        ),
    ]
